### ISSUE TITLE
Support for bearer tokens and/or JWT?

### ISSUE THREAD

**Issue by xogeny** [weluse/hyperagent#38]
I don't see any explicit support for bearer tokens or JWT in hyperagent.  It looks like you could specify headers in the same way you could bundle username and password.

Is the current best practice to simply generate an `Authorization` header to insert the necessary information?  Is there interest in a PR that adds special functionality to explicitly add these somehow?

What I have in mind is the ability to persist a bearer token or JWT so that it is automatically added to each request.  Any issues?  Would a PR for this be accepted?

**Comment by passy** [comment]
I quite like JWT as an idea. What level of support for this would actually be necessary in the library itself?

It seems to me like this should all be handled on the "networking layer" (in quotes, because we won't really leave the application layer as long as we're in JavaScript land). Can't you implement that behavior as part of the `ajax` setup explained here? https://github.com/weluse/hyperagent#instantiating

**Comment by xogeny** [comment]
I think you are correct.  That seems like the simplest way to deal with this and it doesn't require any existing functionality.  I'll close this and assume this solves the problem.  If it doesn't, I'll revisit the issue.  Thanks.

**Comment by c-horn** [comment]
We did this by setting options to configure the underlying ajax.

Our JWT is stored in an HttpOnly cookie:

```
var hyperagent = require('hyperagent')
  , jsCookie = require('js-cookie')

var apirRootURL = '/api'
  , requestHeaders = { 'x-csrf-token': jsCookie.get('csrf-token') }
  , requestOptions = { 'xhrFields': { 'withCredentials': true } };

var apiRoot = new hyperagent.Resource({ 
  url: apirRootURL, 
  headers: requestHeaders,  // adds csrf header
  ajax: requestOptions      // causes JWT to be sent
});
```
