### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by raysuelzer** [weluse/hyperagent#42]
It looks like this project may have been abandoned.  Is it still being maintained by anyone?

**Comment by passy** [comment]
As this terribly late response will clearly indicate, this is not actively maintained at the moment. I consider the library to be Mostly Done™ and built a couple of projects with it in the past where it worked fine for me. I'm still very much interested in fixing bugs that come up and aid people that would like to extend the library as long as this doesn't mean changing the core.

Unfortunately, the time I have available for OSS is incredibly limited these days and I have to spread the little that I have over a lot of projects which is why I can't guarantee any response times.
